envs:
- cluster_name: demo-stg
  compute:
    zone: us-central1-f
  creation_time: "2020-04-17T15:36:49Z"
  last_update_time: "2020-07-14T00:08:40Z"
  name: stg
  namespace: app-cicd-demo2-stg
  project: yuwen-cicd-demo2
- cluster_name: demo-prod
  compute:
    zone: us-central1-f
  creation_time: "2020-06-23T02:42:42Z"
  last_update_time: "2020-06-23T02:47:11Z"
  name: prod
  namespace: app-cicd-demo2-prod
  project: yuwen-cicd-demo2
