apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-admin
subjects:
- kind: ServiceAccount
  name: cicd-sa # {"type":"string","x-kustomize":{"setter":{"name":"ksa","value":"cicd-sa"}}}
  namespace: 'cicd' # {"type":"string","x-kustomize":{"setter":{"name":"namespace","value":"cicd"}}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-sa # {"type":"string","x-kustomize":{"setter":{"name":"ksa","value":"cicd-sa"}}}
  namespace: 'cicd' # {"type":"string","x-kustomize":{"setter":{"name":"namespace","value":"cicd"}}}
secrets:
- name: ssh-key # {"type":"string","x-kustomize":{"setter":{"name":"git-ssh-secret","value":"ssh-key"}}}
- name: gcloud-sa-key # {"type":"string","x-kustomize":{"setter":{"name":"gsa-secret","value":"gcloud-sa-key"}}}
- name: global-appctlconfig # {"type":"string","x-kustomize":{"setter":{"name":"global-appctl-secret","value":"global-appctlconfig"}}}
